### ISSUE TITLE
Future of this project

### ISSUE THREAD

**Issue by SimonSimCity** [spaceraccoon/npm-scan#14]
I have scanned the web up and down to find a package like this after I finally stumbled over this article: https://portswigger.net/daily-swig/js-package-manager-npm-adds-new-security-features-for-web-devs. But after looking at the pull-requests, many have been open for years and some of them fix mission-critical things (like #2).

Since those are open, and the package here is basically unusable as-is, it leaves the question if this repo here is maintained after all. It would be very sad to see a contribution like this going down the sink without proper alternatives in place.

@spaceraccoon can you please speak up? If it is because of time, I'm happy to volunteer in helping to merge and publish. If you've given up on this project in favour of some other project, please let us know.

**Comment by spaceraccoon** [comment]
Thanks @SimonSimCity for the notice - I'll archive this project accordingly, but feel free to reuse the code for your projects as needed! 

The reason for this is the rrowth of alternatives; `npm-audit` was released shortly after our project, while various ecosystem stakeholders like [GitHub](https://github.blog/2021-11-15-githubs-commitment-to-npm-ecosystem-security/) have started their own automated malware scanning services. In the long run, the solution may lie at the server/publisher side of things rather than at the end-user scanners.
